feat(login.sh): private cluster support
drewandersonnz/ocm-container pull request #21
Opened 2020-09-07 08:52 UTC by georgettica

you can now run 'login.sh' on a private cluster and all the required information will be displayed

2020-09-07 09:12 UTC, drewandersonnz commented on container-setup/login.sh
> +	    ocm tunnel -c "${CLUSTERID}" &
can this output be sent to a file on disk for easy review? 

Over time, sshuttle can output more information, colliding with the terminal, I suggest we route all of that to file.

so: 

```
ssh-add
ocm tunnel -c "${CLUSTERID}"  2>&1 > /var/log/ocm-tunnel.log &
sleep 2
tail /var/log/ocm-tunnel.log # to show connection state
```

2020-09-07 09:12 UTC, drewandersonnz commented on container-setup/login.sh
> +            echo "INFO: requested ${CLUSTERID} is private"
whitespace inconsistent

2020-09-07 09:13 UTC, drewandersonnz requested changes
Just a couple of little things.

2020-09-07 09:16 UTC, georgettica commented on container-setup/login.sh
> +	    ocm tunnel -c "${CLUSTERID}" &
what about `tee /var/log/ocm-tunnel.log` should display and save

2020-09-07 09:16 UTC, georgettica commented on container-setup/login.sh
> +            echo "INFO: requested ${CLUSTERID} is private"
saw when reviewed, will change

2020-09-07 09:21 UTC, drewandersonnz commented on container-setup/login.sh
> +	    ocm tunnel -c "${CLUSTERID}" &
the comment is more about redirecting output away from the current terminal, so any debug or status messages don't impact your environment. 

thinking more about it, I wonder if instead of automatically starting the tunnel, we output the information required for the person to copy/paste and start the tunnel, that way they are responsible for how it behaves and are aware of what is going on.

2020-09-07 13:46 UTC, georgettica commented on container-setup/login.sh
> +	    ocm tunnel -c "${CLUSTERID}" &
can we do that? does ocm-tunnel have a dry run option?

2020-09-07 13:47 UTC, georgettica commented on container-setup/login.sh
> +	    ocm tunnel -c "${CLUSTERID}" &
also, if we are adding stuff there, we might suggest adding a $1 for ocm-tunnel so you can `ocm tunnel $CLUSTERID` and not forget the -c

2020-09-08 05:59 UTC, drewandersonnz commented on container-setup/login.sh
> +	    ocm tunnel -c "${CLUSTERID}" &
So I mean, we can:
```
echo ocm tunnel -c "${CLUSTERID}"
```

2020-09-08 06:27 UTC, georgettica commented on container-setup/login.sh
> +	    ocm tunnel -c "${CLUSTERID}" &
ok, will do that

2020-09-08 06:31 UTC, georgettica commented
@drewandersonnz did your reviews, please TAL

2020-09-08 08:48 UTC, merged